version: 0.2

# ARM1 EKS Infrastructure BuildSpec
# This file defines how AWS CodeBuild will deploy Terraform infrastructure

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing Terraform..."
      - wget https://releases.hashicorp.com/terraform/1.6.0/terraform_1.6.0_linux_amd64.zip
      - unzip terraform_1.6.0_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform --version
      
  pre_build:
    commands:
      - echo "Configuring AWS credentials and Terraform backend..."
      - aws sts get-caller-identity
      - cd $CODEBUILD_SRC_DIR
      
  build:
    commands:
      - echo "Initializing Terraform..."
      - terraform init
      - echo "Planning Terraform deployment..."
      - terraform plan -out=tfplan
      - echo "Applying Terraform configuration..."
      - terraform apply -auto-approve tfplan
      
  post_build:
    commands:
      - echo "Terraform deployment completed"
      - terraform output > terraform-outputs.txt
      
artifacts:
  files:
    - terraform-outputs.txt
    - terraform.tfstate
  name: terraform-artifacts

cache:
  paths:
    - '.terraform/**/*'