apiVersion: apps/v1
kind: Deployment
metadata:
  name: arm1-rentzone-deployment
  namespace: default
  labels:
    app: arm1-rentzone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: arm1-rentzone
  template:
    metadata:
      labels:
        app: arm1-rentzone
    spec:
      containers:
      - name: arm1-rentzone-app
        image: 552704151745.dkr.ecr.eu-west-1.amazonaws.com/arm1-rentzone-app:latest
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: arm1-db-secret
              key: DB_HOST
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: arm1-db-secret
              key: DB_DATABASE
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: arm1-db-secret
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: arm1-db-secret
              key: DB_PASSWORD
        - name: APP_NAME
          valueFrom:
            configMapKeyRef:
              name: arm1-app-config
              key: APP_NAME
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: arm1-app-config
              key: APP_ENV
        - name: APP_URL
          valueFrom:
            configMapKeyRef:
              name: arm1-app-config
              key: APP_URL
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        # Health checks temporarily disabled
        # livenessProbe:
        #   httpGet:
        #     path: /health.php
        #     port: 80
        #   initialDelaySeconds: 30
        #   periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /health.php
        #     port: 80
        #   initialDelaySeconds: 5
        #   periodSeconds: 5