apiVersion: v1
kind: Secret
metadata:
  name: arm1-db-secret
  namespace: default
type: Opaque
data:
  # Base64 encoded values - replace with actual encoded values
  DB_HOST: YXJtMS5jcGdpd2RoY3doMXMuZXUtd2VzdC0xLnJkcy5hbWF6b25hd3MuY29t  # arm1.cpgiwdhcwh1s.eu-west-1.rds.amazonaws.com
  DB_DATABASE: QVJNMQ==  # ARM1
  DB_USERNAME: QVJNMQ==  # ARM1
  DB_PASSWORD: QVJNMTQ0MjI2NjQ0  # ARM144226644
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: arm1-app-config
  namespace: default
data:
  APP_NAME: "ARM1-Rentzone"
  APP_ENV: "production"
  APP_DEBUG: "false"
  APP_URL: "https://your-domain.com"  # Update with your actual domain